# Generated by Django 2.2.1 on 2019-05-12 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20190512_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
