# Generated by Django 2.2.1 on 2019-05-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20190512_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ZipCode',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='creditCard',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNo',
            field=models.CharField(max_length=100),
        ),
    ]
