# Generated by Django 2.2.1 on 2019-05-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20190513_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Currency', models.CharField(max_length=100)),
                ('Open', models.CharField(max_length=100)),
                ('Close', models.CharField(max_length=100)),
                ('High', models.CharField(max_length=100)),
                ('Low', models.CharField(max_length=100)),
                ('DayChange', models.CharField(max_length=100)),
                ('StockExchange', models.CharField(max_length=100)),
            ],
        ),
    ]
