# Generated by Django 2.2.1 on 2019-05-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
