# Generated by Django 2.2.1 on 2019-05-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_currency_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
